version: "3"

services:
  front:
    container_name: vue
    restart: always
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
      - /front:/home/skoky/Documents/Projects/TripApp/TripApp/src/API/front
      - /front:/home/skoky/Documents/Projects/TripApp/TripApp/src/front/node_modules
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./API/Dockerfile
    ports:
      - 3306:3306
    depends_on:
      - db
    links:
      - "db:db"
    #env_file:
    #  - ./API/env
    volumes:
      - /API:/home/skoky/Documents/Projects/TripApp/TripApp/src/API/app
    #command: sh /API/start.sh
  db:
    container_name: adonisDB
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    ports:
      - 5434:5434
    #volumes:
    #  - db-data:/var/lib/postgresql/data
#volumes:
#  db-data:
 #   driver: local